### ISSUE TITLE
Where to terminate TLS connections?

### ISSUE THREAD

**Issue by MartiniMoe** [kube-hetzner/kube-hetzner#18]
Hi,

I really appreciate your work and have successfully created my own k8s cluster on the Hetzner cloud :)

Now I wanted to add TLS / HTTPS support and wanted to let the TLS connection terminate on the loadbalancer. Automatically retrieved certificates from letsencrypt seem fine. However the loadbalancer does not seem to work when I change its service 

from 
`"[tcp] 443 -> 31028"`
to 
`"[https] 443 -> 30468"`

I have completely removed the tcp service for port 80, because I think I will not need it.
The loadbalancer shows 'unhealthy' for this service and I cannot access any ingress anymore.

Can someone please advise me on how to achieve TLS support with the hetzner loadbalancer and traefik ingress? :) Thanks!

**Comment by mysticaltech** [comment]
What I do personally is "outsource" SSL to Cloudflare. Will explain exactly how.

**Comment by mysticaltech** [comment]
1- Go to Cloudflare, login to your account, under SSL, create "origin certificates". Those are static certificates that are valid for 15 years.
![ksnip_20220113-223828](https://user-images.githubusercontent.com/518555/149413131-d98761e6-9d43-4e40-9716-4eb7d58bc929.png)

**Comment by mysticaltech** [comment]
2- Save the certificates to two files:

origin-ca.crt
```
-----BEGIN CERTIFICATE-----
-----BEGIN CERTIFICATE-----
```

origin-ca.pk
```
-----BEGIN PRIVATE KEY-----
-----END PRIVATE KEY-----
```

**Comment by mysticaltech** [comment]
3- Add these certificates to Kube with:

`hcloud certificate create --name cloudflare --cert-file origin-ca.crt --key-file origin-ca.pk
`

**Comment by mysticaltech** [comment]
4-  In your ingress manifest and add the follow spec:

```
spec:
  tls:
  - hosts:
    - test.mystical.dev
    secretName: cloudflare-tls
```

**Comment by mysticaltech** [comment]
5- By now when you hit test.yourdomain.dev, you'll be served with Cloudflare static SSL that you have saved to your cluster.  But that is not what we want, that will just serve to secure the communication to Cloudflare itself. 

Go to Cloudflare SSL again, and choose the following setup:
![ksnip_20220113-223809](https://user-images.githubusercontent.com/518555/149414791-3d64c308-f646-4e98-a739-9edcbf13a0fa.png)

**Comment by mysticaltech** [comment]
7- (Optional) Couple that with [external-dns](https://github.com/kubernetes-sigs/external-dns), and you'll be deploying like a boss, without even touching Cloudflare ever again. 

Do deploy it, use:

```
helm install external-dns external-dns/external-dns -f external-dns.values.yaml -n kube-system
```

With this external-dns.values.yaml file:

```
image:
  registry: docker.io
  repository: bitnami/external-dns
  tag: latest
  pullPolicy: Always
env:
  - name: CF_API_KEY
    value: "YOU-CF-API-KEY-HERE"
  - name: CF_API_EMAIL
    value: "me@email.com"
sources:
  - ingress
  - service
policy: sync
provider: cloudflare
logLevel: debug% 
```

Then you can have your ingresses in the following format, and it will create the DNS records automatically:

```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: example-ingress
  annotations:
    "external-dns.alpha.kubernetes.io/hostname": "test.yourdomain.dev"
    "external-dns.alpha.kubernetes.io/cloudflare-proxied": "true"
spec:
  tls:
  - hosts:
    - test.mystical.dev
    secretName: cloudflare-tls
  rules:
    - host: test.yourdomain.dev
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: apple-service
                port:
                  number: 5678%       
```

**Comment by mysticaltech** [comment]
Basically, @MartiniMoe, when you have the above setup once, that's it, the rest just flows automatically, and you do not ever need to configure anything on Hetzner's side, it's all done in the ingress manifest like in the above example. Good luck!

**Comment by MartiniMoe** [comment]
Hi, thank you very much for your detailed explanation!
How comes the certificate is available as a secret in kubernetes at step 4?
I have added my certificate to hetzner cloud via the web ui and I do not have it as a secret in kubernetes.

**Comment by mysticaltech** [comment]
@MartiniMoe You never need to touch the load balancer manually. You let Traefik does its own thing. It configures the LB with the proxy protocol for maximum flexibility. The SSL is added in Kubernetes and shows up automatically on the LB when port 443 is hit. 

Again, everything just works out of the box, you just need to think about feeding the Ingress with a certificate of your choice, either from Let's Encrypt, Traefik can do that, or Cloudflare like I did above.

**Comment by mysticaltech** [comment]
Closing this for now @MartiniMoe, do not hesitate to ask questions if you have some about SSL, but it really is as simple as described above. No manual intervention is needed!

**Comment by MartiniMoe** [comment]
OK, now I understand!
Awesome, thanks! Then I will look into Traefik configuration for Lets Encryp :)

**Comment by mysticaltech** [comment]
Exactly @MartiniMoe, and don't forget Traefik on k3s can be configured via this [HelmChartConfig](https://github.com/kube-hetzner/kube-hetzner/blob/master/templates/traefik_config.yaml.tpl), you can recreate this file, add the acme resolver info for instance like shown [here](https://traefik.io/blog/install-and-configure-traefik-with-helm/) and [here](https://www.corstianboerman.com/blog/2021-03-17/configuring-traefik-on-kubernetes), and it should get you well on your way of making this work!

**Comment by MartiniMoe** [comment]
Thanks! 

At first I wondered why `terraform apply` does not recreate the traefik deployment with the added certificate resolver, but then I figured out, I can just `kubectl apply` the rendered HelmChartConfig after running `terraform apply`.

I already got it to work with my main domain, but not with subdomains 🤔 But maybe thats a DNS issue on my side, I will have to look into it 😄

**Comment by mysticaltech** [comment]
Great to hear, please don't hesitate to post your HelmChartConfig just to help others that would want to do the same in the future.

About subdomains, you have to make sure you request for them with wildcard SSL in the form of *.yourdomain.dev, if already done, then indeed, must be a DNS thing.

**Comment by MartiniMoe** [comment]
Sure, my HelmChartConfig with certificateresolver looks like this:

```
apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: traefik
  namespace: kube-system
spec:
  valuesContent: |-
    service:
      enabled: true
      type: LoadBalancer
      annotations:
        "load-balancer.hetzner.cloud/name": "traefik"
        "load-balancer.hetzner.cloud/use-private-ip": "true"
        "load-balancer.hetzner.cloud/location": "${location}"
        "load-balancer.hetzner.cloud/type": "${lb_server_type}"
        "load-balancer.hetzner.cloud/uses-proxyprotocol": "true"
    additionalArguments:
      - "--entryPoints.web.proxyProtocol.trustedIPs=127.0.0.1/32,10.0.0.0/8"
      - "--entryPoints.websecure.proxyProtocol.trustedIPs=127.0.0.1/32,10.0.0.0/8"
      - "--entryPoints.web.forwardedHeaders.trustedIPs=127.0.0.1/32,10.0.0.0/8"
      - "--entryPoints.websecure.forwardedHeaders.trustedIPs=127.0.0.1/32,10.0.0.0/8"
      - "--certificatesresolvers.letsencrypt.acme.email=<MY-EMAIL-ADDRESS>"
      - "--certificatesresolvers.letsencrypt.acme.storage=/data/acme.json"
      - "--certificatesresolvers.letsencrypt.acme.caserver=https://acme-staging-v02.api.letsencrypt.org/directory"
      - "--certificatesresolvers.letsencrypt.acme.tlschallenge=true"
```
Note that this is using LetsEncrypts staging certificates to not run into rate limiting while testing. For production one should remove the caserver line.

For subdomains I was thinking about letting Traefik get a seperate certificate for each subdomain. Why do you think this wont work and I would need a wildcard certificate? Or did you mention the wildcard certificate because it is easier?
