### ISSUE TITLE
thank you - and quick question about tls 

### ISSUE THREAD

**Issue by TimHeckel** [kube-hetzner/kube-hetzner#68]
Hi - first THANK YOU so much for all the effort you've put into this repository @mysticaltech. I am very new to kubernetes and the whole k3 ecosystem, and your effort to help others is really wonderful. Kudos to you, sir :)

Second - I have a small issue with my TLS and I cannot get it to work. I simply want blog.domain.com to be secured, and though there are lots of ways to get a cert, I'm simply trying to use a wildcard of my own. I've successfully created this using:

`kubectl create secret tls domain-tls --cert ./domain.crt --key ./domain.key`

And I have the ingress set like (bound to a `ghost` deployment)

```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: domain-ingress-blog
spec:
  tls: 
    - hosts: 
      - blog.domain.com
      secretName: domain-tls
  rules:
  - host: blog.domain.com
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: domain-blog-ghost
            port:
              number: 80
```

And I've created an A record pointing the blog.domain.com to the traefik load balancer IP with my dns provider.

I am missing something, though, because the default Traefik cert is always shown when I hit blog.domain.com:

<img width="449" alt="image" src="https://user-images.githubusercontent.com/83935/153761482-a6373b33-97aa-4dc6-8969-8649128e20e2.png">

My Traefik rendered yaml template is below, resulting from the terraform apply:

```
apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: traefik
  namespace: kube-system
spec:
  valuesContent: |-
    service:
      enabled: true
      type: LoadBalancer
      annotations:
        "load-balancer.hetzner.cloud/name": "traefik"
        # make hetzners load-balancer connect to our nodes via our private k3s-net.
        "load-balancer.hetzner.cloud/use-private-ip": "true"
        # keep hetzner-ccm from exposing our private ingress ip, which in general isn't routeable from the public internet.
        "load-balancer.hetzner.cloud/disable-private-ingress": "true"
        # disable ipv6 by default, because external-dns doesn't support AAAA for hcloud yet https://github.com/kubernetes-sigs/external-dns/issues/2044
        "load-balancer.hetzner.cloud/ipv6-disabled": "false"
        "load-balancer.hetzner.cloud/location": "ash"
        "load-balancer.hetzner.cloud/type": "lb11"
        "load-balancer.hetzner.cloud/uses-proxyprotocol": "true"
        # "load-balancer.hetzner.cloud/http-redirect-http": "true"
        "load-balancer.hetzner.cloud/http-sticky-sessions": "true"
    additionalArguments:
      - "--entryPoints.web.proxyProtocol.trustedIPs=127.0.0.1/32,10.0.0.0/8"
      - "--entryPoints.websecure.proxyProtocol.trustedIPs=127.0.0.1/32,10.0.0.0/8"
      - "--entryPoints.web.forwardedHeaders.trustedIPs=127.0.0.1/32,10.0.0.0/8"
      - "--entryPoints.websecure.forwardedHeaders.trustedIPs=127.0.0.1/32,10.0.0.0/8"
```

Any help would be greatly appreciated. Thanks again :)
